dot/rpc: Make request parameter for RPC state_getRuntimeVersion a string
ChainSafe/gossamer pull request #1151
Opened 2020-10-28 19:35 UTC by edwardmack

## Changes

- Make request parameter for RPC method state_getRuntimeVersion a string instead of type modules.StateBlockHashQuery struct (which was causing json unmarshal errors).
-
-

## Tests

```
go test ./dot/rpc/...
```

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [ ] All integration tests and required coverage checks are passing

## Issues

- fixes #1141

2020-10-29 09:05 UTC, arijitAD commented
Run `go mod tidy`
This would fix the go mod file.
Can you point me to the API spec?

2020-10-29 09:06 UTC, arijitAD requested changes
Run `go mod tidy`
This would fix the go mod file.
Can you point me to the API spec?

2020-10-29 14:16 UTC, noot approved these changes

2020-10-29 15:40 UTC, edwardmack commented
Did `go mod tidy`, here is a link to API spec: [https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md](https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md)

2020-11-02 09:11 UTC, arijitAD approved these changes

2020-11-02 17:46 UTC, merged