Added network configuration in CreateInitConfig [#1267]
ChainSafe/gossamer pull request #1283
Opened 2021-01-08 10:01 UTC by anthdm

This PR fixes issue #1267 and prevents future issues around network configuration from the TOML file.

If we take a look at `/cmd/gossamer/main.go L192` what states:

```
// ensure configuration matches genesis data stored during node initialization
// but do not overwrite configuration if the corresponding flag value is set
err = updateDotConfigFromGenesisData(ctx, cfg)
if err != nil {
	logger.Error("failed to update config from genesis data", "error", err)
	return err
}
```

I noticed that we don't set `network` configuration in `CreateInitConfig` hence every value from the Network config will be overwritten to its default state unless we use config flags.

Setting the network configuration in `CreateInitConfig` fixes this issue.

## Changes

-
-
-

## Tests

```

```

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [ ] All integration tests and required coverage checks are passing

## Issues

-

2021-01-08 10:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/gossamer?pullRequest=1283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/gossamer?pullRequest=1283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/gossamer?pullRequest=1283) it.</sub>

2021-01-08 15:20 UTC, arijitAD approved these changes

2021-01-08 16:08 UTC, noot requested changes
this adds the bootnodes from the genesis file into the config, which is ok (but probably should not be the case in the future, since we ideally shouldn't read from the genesis file at all after initialization), but it doesn't allow for new bootnodes to be added via the config file. I added this to the config:
```
bootnodes = ["/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWScfZYBVWr1c2qQHcB8YnXgrjEuXAyCDbRkKkAhhjBijy"]
```

but it's not in the bootnodes list when I ran the node: `./bin/gossamer --config chain/ksmcc/config.toml`
```
INFO[01-08|11:04:29] creating network service...              pkg=dot roles=1 port=7001 bootnodes="[/dns4/p2p.cc3-0.kusama.network/tcp/30100/p2p/12D3KooWDgtynm4S9M3m6ZZhXYu2RrWKdvkCSScc25xKDVSg1Sjd /dns4/p2p.cc3-1.kusama.network/tcp/30100/p2p/12D3KooWNpGriWPmf621Lza9UWU9eLLBdCFaErf6d4HSK7Bcqnv4 /dns4/p2p.cc3-2.kusama.network/tcp/30100/p2p/12D3KooWLmLiB4AenmN2g2mHbhNXbUcNiGi99sAkSk1kAQedp8uE /dns4/p2p.cc3-3.kusama.network/tcp/30100/p2p/12D3KooWEGHw84b4hfvXEfyq4XWEmWCbRGuHMHQMpby4BAtZ4xJf /dns4/p2p.cc3-4.kusama.network/tcp/30100/p2p/12D3KooWF9KDPRMN8WpeyXhEeURZGP8Dmo7go1tDqi7hTYpxV9uW /dns4/p2p.cc3-5.kusama.network/tcp/30100/p2p/12D3KooWDiwMeqzvgWNreS9sV1HW3pZv1PA7QGA7HUCo7FzN5gcA /dns4/kusama-bootnode-0.paritytech.net/tcp/30333/p2p/12D3KooWSueCPH3puP2PcvqPJdNaDNF3jMZjtJtDiSy35pWrbt5h /dns4/kusama-bootnode-0.paritytech.net/tcp/30334/ws/p2p/12D3KooWSueCPH3puP2PcvqPJdNaDNF3jMZjtJtDiSy35pWrbt5h /dns4/kusama-bootnode-1.paritytech.net/tcp/30333/p2p/12D3KooWQKqane1SqWJNWMQkbia9qiMWXkcHtAdfW5eVF8hbwEDw]" protocol=ksmcc3 nobootstrap=false nomdns=false caller=services.go:234
```

please update to read from the config.toml as well! you can append all the bootnodes together in the `*dot.Config`

2021-01-08 16:26 UTC, RyRy79261 approved these changes

2021-01-11 08:31 UTC, anthdm commented
@noot Did you re-initialize the node? Cause basically right now, the fix only works after a re-initializing the node with

 `./bin/gossamer --config chain/gssmr/config.toml --chain gssmr init`

So if I'm right, you want to read the config from the TOML file and update its values even after the node is already initialized?

2021-01-11 18:31 UTC, noot approved these changes

2021-01-11 18:31 UTC, noot commented
@anthdm okay, looks good for now then. the config package needs a good cleanup anyways

2021-01-12 16:14 UTC, merged