chore(lib/common) implement byte pool to improve websocket subscription efficiency
ChainSafe/gossamer pull request #1693
Opened 2021-07-13 23:22 UTC by edwardmack

## Changes

- Issue #1477 outlines suggestions for changes to improve performance during websocket initialization.  This update introduces a byte pool that replaces the random number generator.
-
-

## Tests

```
go test ./lib/common/...
```

## Issues

- closes #1477

2021-07-14 14:26 UTC, EclesioMeloJunior requested changes
I guess we should use `bs.importedBytepool.Put(byte)` in the `Unregister` function

2021-07-14 19:43 UTC, noot commented on dot/state/block.go
> +	finalisedBytepool *common.BytePool
```suggestion
	importedBytePool  *common.BytePool
	finalisedBytePool *common.BytePool
```

2021-07-14 19:45 UTC, noot commented on lib/common/bytepool.go
> +	default: // Discard the buffer if the pool is full.
remove comment

2021-07-15 15:13 UTC, edwardmack commented on dot/state/block.go
> +	finalisedBytepool *common.BytePool
updated.

2021-07-15 15:14 UTC, edwardmack commented on lib/common/bytepool.go
> +	default: // Discard the buffer if the pool is full.
comment removed.

2021-07-15 15:20 UTC, edwardmack commented
> I guess we should use `bs.importedBytepool.Put(byte)` in the `Unregister` function

Good point, I've added this.

2021-07-15 18:00 UTC, EclesioMeloJunior approved these changes

2021-07-21 15:18 UTC, timwu20 approved these changes

2021-07-21 15:18 UTC, timwu20 commented on lib/common/bytepool.go
> +func (bp *BytePool) NumPooled() int {
```suggestion
func (bp *BytePool) Len() int {
```

2021-07-21 19:47 UTC, edwardmack commented on lib/common/bytepool.go
> +func (bp *BytePool) NumPooled() int {
updated.

2021-07-21 20:14 UTC, merged