feat(dot/network) add `network_is_major_syncing` metric
ChainSafe/gossamer pull request #1697
Opened 2021-07-15 14:51 UTC by EclesioMeloJunior

## Changes

- Implement `substrate_sub_libp2p_is_major_syncing` metric as `gossamer_network_is_major_syncing`
- Update the `syncQueue.goal` to be loaded and updated with `atomic`

## Tests

```
go test -timeout 30s -run ^TestSerivceIsMajorSyncMetrics$ github.com/ChainSafe/gossamer/dot/network
```

## Issues

- Related to #1468

2021-07-15 19:39 UTC, timwu20 commented on dot/network/service.go
> +	var issyncing int64
```suggestion
	var isSync int64
```

2021-07-15 19:43 UTC, timwu20 requested changes

2021-07-15 19:43 UTC, timwu20 commented on dot/network/sync.go
> +		t.Reset(time.Second * 5)
nice 👍

2021-07-19 16:26 UTC, noot approved these changes
looks good!

2021-07-21 15:16 UTC, timwu20 approved these changes

2021-07-23 14:27 UTC, merged