fix(lib/grandpa): fix grandpa stall and various bugs
ChainSafe/gossamer pull request #1708
Opened 2021-07-28 15:35 UTC by noot

## Changes

- remove grandpa pause during catch-up functionality for now, as catch-up is buggy and will be fixed in a follow-up
- store greatest finalized round and set ID in database in specific key, previously was using (0,0) to designate this but wasn't always correct
- TODO: look into message handler stall
- TODO: look into round stall when it appears 2/3 votes are present

## Tests

```
go test ./dot/state
go test ./lib/grandpa -short
```

## Issues

- related to #592

2021-08-04 19:11 UTC, EclesioMeloJunior requested changes

2021-08-04 19:44 UTC, noot commented on dot/state/block_finalisation.go
>  	bs.lastFinalised = hash
we don't want it to set `lastFinaliasedHash` if there's some error, and also this function is atomic due to the locking, so doesn't make a difference I don't think

2021-08-04 19:45 UTC, noot commented on dot/state/block_finalisation.go
> +	return bs.db.Put(highestRoundAndSetIDKey, roundSetIDKey(round, setID))
updated!

2021-08-04 19:56 UTC, EclesioMeloJunior commented on dot/state/block_finalisation.go
>  	bs.lastFinalised = hash
got it!

2021-08-05 21:13 UTC, EclesioMeloJunior requested changes

2021-08-05 21:14 UTC, EclesioMeloJunior commented on lib/grandpa/message_tracker.go
> +	// TODO: change to map of maps, this allows duplicates
created issue #1718 for this TODO

2021-08-05 21:19 UTC, noot commented on lib/grandpa/grandpa.go
> +			continue
added!

2021-08-05 21:37 UTC, EclesioMeloJunior approved these changes

2021-08-05 22:58 UTC, merged