Implement uint128 field encoding for genesis.
ChainSafe/gossamer pull request #1732
Opened 2021-08-16 15:20 UTC by arijitAD

## Changes

- Implement uint128 field encoding for genesis.

## Tests

```

```

## Issues

-

## Primary Reviewer 

- @timwu20

2021-08-16 20:42 UTC, edwardmack approved these changes

2021-08-16 20:42 UTC, edwardmack commented on lib/genesis/pallet.go
> +	MaxMembers *scale.Uint128 `json:"MaxMembers"` // TODO: figure out the type
remove todo

2021-08-17 12:15 UTC, arijitAD commented
<img width="667" alt="Screenshot 2021-08-17 at 5 45 24 PM" src="https://user-images.githubusercontent.com/5843604/129723932-351e72ae-9dbc-4277-91f7-e6b6efb59fa9.png">
Code coverage is passing for me locally.

2021-08-17 13:21 UTC, EclesioMeloJunior requested changes

2021-08-17 13:21 UTC, EclesioMeloJunior commented on pkg/scale/uint128.go
> +	copy(buf, data)
the `buf` variable is not being used

2021-08-17 13:42 UTC, arijitAD commented on lib/genesis/pallet.go
> +	MaxMembers *scale.Uint128 `json:"MaxMembers"` // TODO: figure out the type
Done

2021-08-17 13:45 UTC, arijitAD commented on pkg/scale/uint128.go
> +	copy(buf, data)
Done.

2021-08-17 13:50 UTC, EclesioMeloJunior approved these changes
lgtm

2021-08-17 15:18 UTC, merged