Omar/child storage
ChainSafe/gossamer pull request #1900
Opened 2021-10-15 12:18 UTC by omar391

## Changes

- Added test cases for `GetStorageFromChild`
-
-

## Tests

```
go test -timeout 30s -run ^TestStorage_StorageChild$ github.com/ChainSafe/gossamer/dot/state
```

## Issues

- closes #1490

## Primary Reviewer 

@EclesioMeloJunior 
-

2021-11-11 14:00 UTC, EclesioMeloJunior requested changes

2021-11-11 14:00 UTC, EclesioMeloJunior commented on dot/state/storage_test.go
> +	err = digest.Add(*types.NewBabeSecondaryPlainPreDigest(0, 1).ToPreRuntimeDigest())
```suggestion
	_, err = digest.Add(*types.NewBabeSecondaryPlainPreDigest(0, 1).ToPreRuntimeDigest())
```

2021-11-25 16:04 UTC, omar391 commented on dot/state/storage_test.go
> +		require.NoError(t, err)
@noot its resolved!

2021-11-25 16:16 UTC, omar391 commented on dot/state/storage_test.go
> +			err:      nil,
Done.

2021-11-25 16:18 UTC, omar391 commented on dot/state/storage_test.go
> +		}
Done

2021-11-29 21:00 UTC, noot commented
going to close this for now as it doesn't address the issue

2021-11-29 21:00 UTC, closed without merging