fix: Staging CI workflow
ChainSafe/gossamer pull request #2034
Opened 2021-11-12 15:39 UTC by timwu20

## Changes

- Staging branch workflow was broken by another commit
-
-

## Tests

- push to staging and ensure Kusama and Polkadot nodes are deployed

## Issues

-

## Primary Reviewer

- @qdm12

2021-11-12 15:44 UTC, qdm12 requested changes

2021-11-12 15:59 UTC, noot approved these changes

2021-11-15 12:35 UTC, EclesioMeloJunior approved these changes

2021-11-16 18:46 UTC, qdm12 approved these changes
Thanks!

2021-11-16 19:01 UTC, merged