fix(dot/network): increase max message size from 64KB to 100KB
ChainSafe/gossamer pull request #2291
Opened 2022-02-11 21:02 UTC by qdm12

## Changes

- See why in #2288 

## Tests

## Issues

- Related to #2288

## Primary Reviewer

- @noot

2022-02-14 16:14 UTC, kishansagathiya approved these changes

2022-02-14 16:16 UTC, noot requested changes
why 100kb exactly? we might still receive messages larger than this, we should just change it to dynamically get more buffers if the size is larger

2022-02-14 23:21 UTC, qdm12 commented
> why 100kb exactly? we might still receive messages larger than this

We receive up to 78KB messages as far as I've seen in the logs. This was an ugly quick fix to not drop them, a better more complex fix would be to use `*bytes.Buffer` as suggested in the issue so we can have dynamic sizes.

I changed it to increase the buffer slice size when needed, although the bytes.Buffer's `Grow` method is really more appropriate here.

2022-02-16 19:50 UTC, noot approved these changes

2022-02-17 15:34 UTC, merged