chore(golang-ci): upgrade `golangci-lint` to `v1.45`
ChainSafe/gossamer pull request #2434
Opened 2022-03-24 18:41 UTC by EclesioMeloJunior

## Changes

- In order to check golang 1.18 generic code we should upgrade golangci-lint to version `v1.45`
- Fixes PR https://github.com/ChainSafe/gossamer/pull/2339 CI

## Tests

```
N/A
```

## Issues

- N/A

## Primary Reviewer

- @qdm12

2022-03-24 18:45 UTC, qdm12 approved these changes

2022-03-25 10:33 UTC, qdm12 requested changes

2022-03-25 10:33 UTC, qdm12 commented on dot/rpc/modules/grandpa.go
> +	if req.authorityID != uint64(0) { //// nolint:staticcheck
I would like to suggest to leave these `//nolint` comments here as they were before, and comment out the linters not working with Go 1.18 in `.golangci-lint.yml`, and add custom rules to `nolintlint` such that it ignores `//nolint` comments for these disabled linters.

I'll monitor when these get fixed to work with generics and will re-add them over time.

2022-03-25 14:48 UTC, qdm12 commented on .golangci.yml
> +      source: "^?//nolint(:staticcheck)?"
Don't we need one for `bodyclose`, `nilerr` and `unparam` as well? :thinking: 

Also I think the regex shouldn't start with `^` if the comment if put at the end of a line right?

2022-03-25 14:52 UTC, qdm12 requested changes

2022-03-25 14:52 UTC, qdm12 commented on .golangci.yml
> +      source: "^?//nolint(:staticcheck)?"
Oh I get it, can you change that source to

```suggestion
      source: "//nolint:[bodyclose|nilerr|staticcheck|unparama]"
```

And remove that single `//nolint` you found (it was a false positive from staticcheck I think)

2022-03-25 15:12 UTC, qdm12 approved these changes

2022-03-25 18:32 UTC, noot approved these changes

2022-03-25 19:11 UTC, merged