fix(state/epoch): assign epoch 1 when block number is 0
ChainSafe/gossamer pull request #2592
Opened 2022-06-08 14:11 UTC by EclesioMeloJunior

## Changes

- The genesis block does not contain any BABE digest since this information is already persisted using the information in the `spec.json`

## Tests

When you start the gossamer node you should not see 
```
2022-06-08T17:52:16+05:30 EROR failed to persist babe next epoch data: cannot get epoch for block 0 (0xee87cc7ac5e87460094ec4ba29bbf8f28fb7741b69e7edb142233c3dd990b365): header does not contain pre-runtime digest	digest.go:L244	pkg=digest
2022-06-08T17:52:16+05:30 EROR failed to persist babe next epoch config: cannot get epoch for block 0 (0xee87cc7ac5e87460094ec4ba29bbf8f28fb7741b69e7edb142233c3dd990b365): header does not contain pre-runtime digest	digest.go:L249	pkg=digest
```
## Issues

- Related #2591

## Primary Reviewer

@kishansagathiya

2022-06-08 15:05 UTC, kishansagathiya approved these changes

2022-06-08 18:58 UTC, EclesioMeloJunior commented
> Nice 👍
> 
> Probably a dumb question, but should we force-set the BABE digest for the first block finalized header somewhere above in the call stack?

This is a good question and I think it is possible but requires a larger refactor

2022-06-08 19:22 UTC, timwu20 requested changes

2022-06-08 19:22 UTC, timwu20 commented on dot/state/epoch.go
> +	if finalizedHeader.Number == 0 {
Can we add this check once in `Handler.HandleBlockFinalisation` instead of in both of these functions?

2022-06-09 16:57 UTC, qdm12 approved these changes

2022-06-09 17:19 UTC, timwu20 approved these changes

2022-06-09 19:31 UTC, merged