fix(lib/babe): check if authority index is in the `authorities` range
ChainSafe/gossamer pull request #2601
Opened 2022-06-13 19:46 UTC by EclesioMeloJunior

## Changes

- Check for negative numbers after casting a value to `int`

## Tests

N/A

## Issues

- Closes #2415

## Primary Reviewer

@jimjbrettj

2022-06-14 21:44 UTC, timwu20 requested changes
`authIndex` is undefined

2022-06-15 13:50 UTC, qdm12 approved these changes

2022-06-15 14:57 UTC, jimjbrettj approved these changes

2022-06-16 13:06 UTC, qdm12 commented
@timwu20 we need you to approve 😉 

Also regarding your comment, it might had been your IDE/language server going crazy? 🤔 

> `authIndex` is undefined

2022-06-21 12:09 UTC, merged