fix(dot/sync): Fix flaky tests `Test_chainSync_logSyncSpeed` and `Test_chainSync_start`
ChainSafe/gossamer pull request #2610
Opened 2022-06-16 16:56 UTC by qdm12

## Changes

- Production code had to be refactored to be event driven
- Fix `Test_chainSync_logSyncSpeed` to be fully event driven
- Fix `Test_chainSync_start` to be fully event driven

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer/dot/sync/...
```

## Issues

## Primary Reviewer

@timwu20

2022-06-16 19:07 UTC, EclesioMeloJunior requested changes

2022-06-16 19:07 UTC, EclesioMeloJunior commented on dot/sync/chain_sync_test.go
> +		networkBuilder    func(ctrl *gomock.Controller, cancel context.CancelFunc) Network
```suggestion
		networkBuilder    func(ctrl *gomock.Controller) Network
```

2022-06-16 19:07 UTC, EclesioMeloJunior commented on dot/sync/chain_sync_test.go
> +				networkBuilder: func(ctrl *gomock.Controller, cancel context.CancelFunc) Network {
```suggestion
				networkBuilder: func(ctrl *gomock.Controller) Network {
```

2022-06-16 19:07 UTC, EclesioMeloJunior commented on dot/sync/chain_sync_test.go
> +				networkBuilder: func(ctrl *gomock.Controller, cancel context.CancelFunc) Network {
```suggestion
				networkBuilder: func(ctrl *gomock.Controller) Network {
```

2022-06-16 19:07 UTC, EclesioMeloJunior commented on dot/sync/chain_sync_test.go
> +				network:        tt.fields.networkBuilder(ctrl, cancel),
```suggestion
				network:        tt.fields.networkBuilder(ctrl),
```

2022-06-16 19:40 UTC, EclesioMeloJunior approved these changes

2022-06-17 15:40 UTC, timwu20 approved these changes

2022-06-17 15:54 UTC, edwardmack approved these changes

2022-06-17 16:26 UTC, merged