Make sure message that we receive are below their threshold sizes
ChainSafe/gossamer pull request #2628
Opened 2022-06-29 11:38 UTC by kishansagathiya

## Changes

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues
Fixes #2399

## Primary Reviewer

@timwu20

2022-07-04 09:54 UTC, kishansagathiya commented on pkg/scale/decode.go
> +	// check the length
```suggestion
```

2022-07-04 18:01 UTC, EclesioMeloJunior requested changes

2022-07-04 18:01 UTC, EclesioMeloJunior commented on dot/network/utils.go
> +
could you change them to `const`?

2022-07-06 14:24 UTC, EclesioMeloJunior approved these changes

2022-07-06 15:13 UTC, timwu20 approved these changes

2022-07-07 04:17 UTC, merged