fix(lib/grandpa): update grandpa protocol ID
ChainSafe/gossamer pull request #2678
Opened 2022-07-15 21:59 UTC by EclesioMeloJunior

## Changes

- Update GRANDPA protocol id from `/paritytech/grandpa/1` to `/{genesis_hash}/grandpa/1` as described here -> https://github.com/ChainSafe/gossamer/issues/2623#issuecomment-1185115378

## Tests

N/A

## Issues

- Closes #2701

## Primary Reviewer

@jimjbrettj

2022-07-18 14:43 UTC, qdm12 approved these changes

2022-07-18 14:43 UTC, qdm12 commented on lib/grandpa/network.go
> +// TODO: should we remove the SubProtocol mehtod from the `Message` interface?
So.. should we? 😄 Also

```suggestion
// TODO: should we remove the SubProtocol method from the `Message` interface?
```

2022-07-19 17:21 UTC, timwu20 approved these changes

2022-07-19 19:06 UTC, qdm12 requested changes

2022-07-19 19:06 UTC, qdm12 commented on lib/grandpa/network.go
> +	neighbourMessageInterval = time.Minute * 5
pedantic nit / out of scope: unit should be at the end


```suggestion
	neighbourMessageInterval = 5 * time.Minute
```

2022-07-19 19:06 UTC, qdm12 commented on lib/grandpa/network.go
> +// TODO: should we remove the SubProtocol method from the `Message` interface?
Please link to an issue or do it in this PR

2022-07-19 19:06 UTC, qdm12 commented on lib/grandpa/network_test.go
> +	go gs.sendNeighbourMessage(time.Second)
shouldn't this be

```suggestion
	go gs.sendNeighbourMessage(neighbourMessageInterval)
```

2022-07-19 21:54 UTC, jimjbrettj approved these changes
lgtm

2022-07-20 09:10 UTC, kishansagathiya requested changes
Can you post some relevant logs for this, like dump of substrate std output and gossamer std output?

When I look at the specs I see the protocol id to be `/dot/grandpa/1`, but `/paritytech/grandpa/1` is still supported, so things should work. We should as well try to support both.

![Screenshot from 2022-07-20 14-34-11](https://user-images.githubusercontent.com/10185999/179943405-26f2233d-5c2a-47d7-8fb1-67b25466fc61.png)

https://spec.polkadot.network/#sect-protocols-substreams

2022-07-20 12:51 UTC, EclesioMeloJunior commented
@kishansagathiya the protocol `/dot/grandpa/1` is not supported anymore and the protocol ID `/paritytech/grandpa/1` is marked as a legacy in substrate -> https://github.com/paritytech/substrate/blob/7b81072843e584ef2bee449081aed5c963021ee9/client/finality-grandpa/src/communication/mod.rs#L70, and there is an issue that describes the change -> https://github.com/paritytech/substrate/issues/7746. 

About the logs:

1. Substrate connects to another substrate and propagates messages using the new protocol ID
```
TRACE tokio-runtime-worker gossip: Registering peer who=12D3KooWFv664Y2BcR6J6eMdKuLsDGuZCFHVq6DT7mLyw6FFL4gp protocol=/588e9db899afbea5641b365fc750bcea90403573919f85d4fb2474d9057ac005/grandpa/1 role=Authority

TRACE tokio-runtime-worker gossip: Propagating message to=12D3KooWFv664Y2BcR6J6eMdKuLsDGuZCFHVq6DT7mLyw6FFL4gp protocol=/588e9db899afbea5641b365fc750bcea90403573919f85d4fb2474d9057ac005/grandpa/1
```

2. After a gossamer node started using the `/paritytech/grandpa/1`

```
INFO registered notifications sub-protocol /paritytech/grandpa/1	service.go:L538	pkg=network
Started listening on /ip4/127.0.0.1/tcp/7002/p2p/12D3KooWJ9TpY3zFzm8TzHpDKAdL4BKQu8HuZgn1kp7aKiQyZeF8
```

Substrate registered gossamer using the new protocol ID:

```
TRACE tokio-runtime-worker gossip: Registering peer who=12D3KooWJ9TpY3zFzm8TzHpDKAdL4BKQu8HuZgn1kp7aKiQyZeF8 protocol=/588e9db899afbea5641b365fc750bcea90403573919f85d4fb2474d9057ac005/grandpa/1 role=Authority
```

and propagate the message to gossamer using the new protocol ID as well:

```
TRACE tokio-runtime-worker gossip: Propagating message to=12D3KooWJ9TpY3zFzm8TzHpDKAdL4BKQu8HuZgn1kp7aKiQyZeF8 protocol=/588e9db899afbea5641b365fc750bcea90403573919f85d4fb2474d9057ac005/grandpa/1
```

here are the dumps -> https://gist.github.com/EclesioMeloJunior/f2271f1bc70dbf84fe7b427c4a60500d

2022-07-21 17:26 UTC, qdm12 approved these changes

2022-07-26 14:52 UTC, kishansagathiya approved these changes

2022-07-26 18:16 UTC, merged