fix(dot/babe): use `bs.latestFinalised` instead of using `round/set id`
ChainSafe/gossamer pull request #3167
Opened 2023-03-21 15:20 UTC by EclesioMeloJunior

## Changes

- This change fixes the problem where:
  - While syncing in the Westend chain Gossamer stores the finalized block hash bounding it to its respective round and set id, but in Westend happened updates to validators where they restarted the finalization in the same set id but reset the round counter. As described in https://github.com/ChainSafe/gossamer/issues/3150, we synced block 198,656 with round 106 and set 314 and then we synced block 198,785 with round *3* and set id 314
  - The fact that a higher block contains a lower round for the same set id was ignored by Gossamer, which means that Gossamer finalizes block 198,785 but did not bound the hash with the round and set id
  - When the next synced block arrives to be verified and finalized Gossamer understands that the latest finalized block is 198,656 and the `RangeInMemory` method fails to find that block since it is already pruned from memory.

- In `handleFinalisedBlock` use `bs.latestFinalised` instead of using `round/set id`
- Remove from `setHighestRoundAndSetID` the verification of the given round and set id compared to the current round and set id. 

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

## Primary Reviewer

@timwu20

2023-03-21 15:26 UTC, EclesioMeloJunior commented
This strict validation was removed since in Westend there are a lot of weird cases that lead to rounds being messed up in the same set id, but I still wondering about adding an option called `validation-while-syncing` with 2 modes `relaxed` and `strict` than we can make this validation strict while syncing against Kusama/Polkadot and make it relaxed while syncing against Westend. @danforbes

2023-03-24 14:19 UTC, kishansagathiya approved these changes

2023-03-27 13:56 UTC, dimartiro approved these changes

2023-03-27 23:09 UTC, jimjbrettj commented
It seems that in state tests in block_finalization_test.go that TestHighestRoundAndSetID is failing

2023-03-27 23:12 UTC, jimjbrettj commented on dot/state/block_finalisation.go
> -	if setID < currSetID || setID == currSetID && round <= currRound {
I know that for relaxed mode we don't need to verify the round number, but do we also now skip verifying that the setId is greater?

2023-03-27 23:18 UTC, jimjbrettj requested changes
Looks good, just need to fix failing tests

2023-03-28 19:39 UTC, jimjbrettj approved these changes
Nice work!

2023-03-28 20:19 UTC, merged