feat(sync): Add badBlocks support
ChainSafe/gossamer pull request #3214
Opened 2023-04-17 17:57 UTC by dimartiro

## Changes

Change sync process to reject bad blocks and disconnect from that peer

## Tests

```sh
make test
```

## Issues

https://github.com/ChainSafe/gossamer/issues/3202

## Primary Reviewer

@EclesioMeloJunior

2023-04-17 19:37 UTC, EclesioMeloJunior requested changes

2023-04-17 19:37 UTC, EclesioMeloJunior commented on dot/sync/chain_sync.go
> +
```suggestion
if slices.Contains(cs.badBlocks, bd.Hash.String) {
    logger.Errorf("Rejecting known bad block Number: %d Hash: %s", bd.Number(), bd.Hash)
    return errBadBlock
}
```

2023-04-17 22:40 UTC, dimartiro commented on dot/sync/chain_sync.go
> +
Done! Thks for the suggestion

2023-04-19 14:39 UTC, dimartiro commented
I'll close this PR cause I splitted it in two, [this is one](https://github.com/ChainSafe/gossamer/pull/3220) and the second one will be using Eclesio's branch with the new sync to use this validation there

2023-04-19 14:39 UTC, closed without merging