Add extra required runtime imports for parachain validation
ChainSafe/gossamer pull request #3254
Opened 2023-05-11 14:18 UTC by kishansagathiya

This PR adds following import calls:
- ext_default_child_storage_clear_prefix_version_2
- ext_default_child_storage_root_version_2
- ext_offchain_index_clear_version_1

## Changes

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

#2989

## Primary Reviewer

@timwu20

2023-07-11 09:54 UTC, kanishkatn approved these changes
looks good!

2023-07-11 13:46 UTC, kishansagathiya commented
A corresping PR in polkadot spec repo for tests to work https://github.com/ChainSafe/polkadot-spec/pull/15

2023-07-19 14:26 UTC, EclesioMeloJunior requested changes

2023-07-19 14:26 UTC, EclesioMeloJunior commented on lib/runtime/wasmer/imports_test.go
> +func Test_ext_default_child_storage_clear_prefix_version_2(t *testing.T) {
Could you include a test when the limit is not 0?

2023-07-19 14:26 UTC, EclesioMeloJunior commented on lib/runtime/wasmer/imports.go
> +	return C.int64_t(0)
Following the spec the returned value should be a pointer-size to the following variant:

- Variant 0 indicates that all keys of the child storage have been removed, followed by the number of removed keys
- Variant 1 indicates that there are remaining keys, followed by the number of removed keys.

ref: https://spec.polkadot.network/chap-host-api#id-version-2-prototype-3

You can see how they implemented it in substrate:

```rs
#[derive(PassByCodec, Encode, Decode)]
pub enum KillStorageResult {
	/// All keys to remove were removed, return number of iterations performed during the
	/// operation.
	AllRemoved(u32),
	/// Not all key to remove were removed, return number of iterations performed during the
	/// operation.
	SomeRemaining(u32),
}

#[version(2)]
fn clear_prefix(&mut self, prefix: &[u8], limit: Option<u32>) -> KillStorageResult
```
- clear prefix v2: https://github.com/paritytech/substrate/blob/d58481569817f4a2074dbab014fa629dea7e0ec9/primitives/io/src/lib.rs#L186
- the returned variant: https://github.com/paritytech/substrate/blob/d58481569817f4a2074dbab014fa629dea7e0ec9/primitives/io/src/lib.rs#L96

2023-07-26 11:52 UTC, EclesioMeloJunior approved these changes
LGTM, just a small suggestion

2023-07-26 11:52 UTC, EclesioMeloJunior commented on lib/runtime/storage/trie.go
> +	}
```suggestion
	if err != nil || child == nil {
		return 0, false, err
	}
```

2023-07-27 07:53 UTC, merged