Replace usages of .AnyTimes() with .Times(n)
ChainSafe/gossamer pull request #3291
Opened 2023-05-31 11:32 UTC by axaysagathiya

closes #3038

## Changes
Changed AnyTime() with Times() from multiple tests. 

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues
#3038 

## Primary Reviewer

@timwu20

2023-05-31 15:30 UTC, EclesioMeloJunior requested changes
Nice changes!! 🚀

2023-05-31 15:32 UTC, EclesioMeloJunior requested changes

2023-05-31 15:32 UTC, EclesioMeloJunior commented on dot/rpc/subscription/listeners_integration_test.go
> +	TxStateAPI.EXPECT().FreeStatusNotifierChannel(gomock.Any()).Times(1)
The calls the has `Times(1)` you can leave it without the `Times(1)`, like:
```suggestion
	TxStateAPI.EXPECT().FreeStatusNotifierChannel(gomock.Any())
```

2023-05-31 20:28 UTC, dimartiro approved these changes

2023-06-01 05:28 UTC, kishansagathiya approved these changes

2023-06-01 05:38 UTC, merged