fix(lib/runtime): update `MaxPossibleAllocation` to `2^25`
ChainSafe/gossamer pull request #3393
Opened 2023-07-19 20:38 UTC by EclesioMeloJunior

## Changes

This changes increases the amount of possible allocations from `2 ^ 24` to `2 ^ 25` as it is defined in substrate `primitives/core` 

```rs
pub const MAX_POSSIBLE_ALLOCATION: u32 = 33554432; // 2^25 bytes, 32 MiB
```
ref: https://github.com/paritytech/substrate/blob/2ca66197161b3b5c4e2aafdb7238f3c5af84a0e8/primitives/core/src/lib.rs#L400

This fixes the following error while syncing

![image](https://github.com/ChainSafe/gossamer/assets/17255488/c60bab96-3934-4e75-b029-7dbabe2a38c1)

## Tests

Above block 6M the amount of extrinsics in the retrieved blocks increases 

## Issues

N/A

## Primary Reviewer

@dimartiro

2023-07-19 21:38 UTC, dimartiro approved these changes
LGTM

2023-07-19 21:39 UTC, dimartiro requested changes
There are some linting errors due arrays using 22 as max cap

2023-07-20 16:02 UTC, dimartiro requested changes
I think you should fix [this test ](https://github.com/ChainSafe/gossamer/blob/4ea3361cb9d69300c74a053dd44d1108847b8068/lib/runtime/allocator_test.go#L486-L492) too

This could be a possible way to fix it:

```Go
func TestShouldGetMaxFromIndex(t *testing.T) {
	index := uint(HeadsQty - 1)
	itemSize := getItemSizeFromIndex(index)
	if itemSize != MaxPossibleAllocation {
		t.Errorf("item_size should be %d, got item_size: %d", MaxPossibleAllocation, itemSize)
	}
}
```

2023-07-20 19:02 UTC, dimartiro approved these changes

2023-07-20 19:10 UTC, jimjbrettj approved these changes

2023-07-20 19:10 UTC, merged