fix: add a limit of number of bytes while scale decoding a slice
ChainSafe/gossamer pull request #3733
Opened 2024-02-01 09:57 UTC by kishansagathiya

While scale decoding we first read the length of bytes to decode and then we decode that many bytes.

Someone could ask us to decode some malicious bytes such that the read length is unreasonably big. In such case, we would have to create a byte slice as big as the length. So, we would either panic because of `makeslice: len out of range` or because the asked length would be more than the memory we have available in our machine.

Both of these are the situations we don't want. Hence, I have put a limit on decodable bytes (maxDecodableBytes), 16MB. I have kept it 16MB because for the usecase of polkadot specs, we would never need to decode a bigger set of bytes.

## Changes

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

Fixes #3476 

## Primary Reviewer

@timwu20 @EclesioMeloJunior

2024-02-02 01:29 UTC, EclesioMeloJunior approved these changes
LGTM!

2024-02-02 01:29 UTC, EclesioMeloJunior commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
Given that scale encoded slices are prepended with its size and given the fact that golang's  `make([]T, size)` only accepts the size as `int` I would suggest using `math.MaxInt`

2024-02-02 13:07 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
math.MaxInt is 9223372036854775807. Creating a byte slice of that length would require significant memory (8589934592 GB).

2024-02-02 18:10 UTC, jimjbrettj commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
You said 16 was the largest response we have seen so far right? Is it a worthy trade off to increase it a bit in case we receiver larger messages in the future or is this not to much of a concern? I like the point you made about just worrying about polkadot support for now, just was wondering if we could receive bigger messages within that context

2024-02-02 18:10 UTC, jimjbrettj approved these changes

2024-02-02 18:24 UTC, dimartiro commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
How is parity's scale crate handling this case?

2024-02-05 08:38 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
> How is parity's scale crate handling this case?
It panics!

2024-02-05 14:55 UTC, EclesioMeloJunior requested changes

2024-02-05 14:55 UTC, EclesioMeloJunior commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
@kishansagathiya I agree that this is a large value but since our `pkg/scale` is a stand-alone lib I don't think is a good approach to put 16kb as the `maxDecodableBytes` given that this is a limit specific for our use case/polkadot implementation. Other libraries that use our scale pkg may not have the same limit or any limit.

Another point is: `parity-scale-codec` has a limitation bound to `U32::MAX` for encoding and decoding
- encoding: see https://github.com/paritytech/parity-scale-codec/blob/8c3cc7f2311c8ea7522f4edc21d9cf1f7b661519/src/codec.rs#L1088
- decoding: see https://github.com/paritytech/parity-scale-codec/blob/8c3cc7f2311c8ea7522f4edc21d9cf1f7b661519/src/codec.rs#L1181

So I keep my suggestion to add a limitation in the stand-alone scale pkg lib to `math.MaxUint32`

2024-02-05 15:23 UTC, dimartiro commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
Isn't it a known issue? https://github.com/paritytech/parity-scale-codec?tab=readme-ov-file#known-issues

2024-02-07 15:44 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
> 16kb as the maxDecodableBytes
16MB, not KB

> Another point is: parity-scale-codec has a limitation bound to U32::MAX for encoding and decoding

True. The problem is to prevent us from an attacker who misuses this and make us create a giant array for no good reason.
I can keep u32 max as the bound. I will have to use read bytes in a small buffers instead of declaring a huge array at the same time. That's what parity-scale-codec does. I will push with those changes.

tagging @timwu20 to confirm.  

> Isn't it a known issue? https://github.com/paritytech/parity-scale-codec?tab=readme-ov-file#known-issues

Yeah, I think they are saying that, even though we support such ridiculous size, chances are your machine memory can't take it so you will get stack overflow.

2024-02-08 14:59 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
I think I have figured out why this is happening. 
I rust the error is `u32 out of range`, because block number there is u32. Inside header, we have kept block number uint. When we decode using `decodeUint`, the execution goes to https://github.com/ChainSafe/gossamer/blob/1c0c20347b4cbabcae68c2d733ff452055af6459/pkg/scale/decode.go#L539, which is for uint64.

I wonder if we should change block number to uint32 instead of just uint.

2024-02-08 14:59 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
I think I have figured out why this is happening. 
I rust the error is `u32 out of range`, because block number there is u32. Inside header, we have kept block number uint. When we decode using `decodeUint`, the execution goes to https://github.com/ChainSafe/gossamer/blob/1c0c20347b4cbabcae68c2d733ff452055af6459/pkg/scale/decode.go#L539, which is for uint64.

I wonder if we should change block number to uint32 instead of just uint.

2024-02-08 15:13 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
I think I know why this is happening. 
In rust, the error is `u32 out of range`. I think it decodes length as `Compact<u32>`. 

In `decodeUint`, we have combined logic to decode both `Compact<u32>` and `Compact<u64>`. The execution in gossamer goes to https://github.com/ChainSafe/gossamer/blob/2fcb906aec425e1658e0e559a92da5813309ffbc/pkg/scale/decode.go#L539, which is for uint64.

2024-02-08 15:27 UTC, dimartiro commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
I believe they are using `Compact<u64>` based on this:

https://github.com/paritytech/scale-decode/blob/c5744c9e39e92a4f75e86c1b226fa162fed4e08b/scale-decode/src/visitor/types/sequence.rs#L33-L45

2024-02-08 15:38 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
> I believe they are using Compact<u64> based on this:

Naah, Look at the error that I get while trying to decode this in rust. It says `out of range decoding Compact<u32>`, so, it is trying to decode Compact<u32>. 
Plus, I have been debugging with breakpoints, so I know execution is going to  https://github.com/paritytech/parity-scale-codec/blob/8c3cc7f2311c8ea7522f4edc21d9cf1f7b661519/src/compact.rs#L498 and fails at https://github.com/paritytech/parity-scale-codec/blob/8c3cc7f2311c8ea7522f4edc21d9cf1f7b661519/src/compact.rs#L531
```
running 1 test
thread 'generic::header::tests::ensure_format_is_unchanged' panicked at 'called `Result::unwrap()` on an `Err` value: Error { cause: Some(Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "out of range decoding Compact<u32>" }), desc: "Could not decode `Digest::logs`" }), desc: "Could not decode `Header::digest`" }), desc: "Could not decode `Block::header`" }', substrate/primitives/runtime/src/generic/header.rs:214:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1076:23
   4: sp_runtime::generic::header::tests::ensure_format_is_unchanged
             at ./src/generic/header.rs:214:17
   5: sp_runtime::generic::header::tests::ensure_format_is_unchanged::{{closure}}
             at ./src/generic/header.rs:209:34
   6: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test generic::header::tests::ensure_format_is_unchanged ... FAILED
```

2024-02-09 09:36 UTC, kishansagathiya commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
https://github.com/paritytech/parity-scale-codec/blob/8c3cc7f2311c8ea7522f4edc21d9cf1f7b661519/src/codec.rs#L1180-L1181

This shows that length is Compact<u32>

2024-02-09 13:08 UTC, dimartiro commented on pkg/scale/decode.go
> +var maxDecodableBytes = uint(1024 * 1024 * 16)
You are totally right Kishan! The one I sent was for sequences not Vec.

Good finding! 👏🏻

2024-02-12 11:29 UTC, EclesioMeloJunior approved these changes

2024-02-12 14:09 UTC, dimartiro approved these changes

2024-02-12 14:13 UTC, merged