Collator Protocol Collator Side Skeleton
ChainSafe/gossamer pull request #3825
Opened 2024-03-28 10:00 UTC by kishansagathiya

This commit introduces collator side of the collator protocol. This is just a skeleton that
- implements the SubSystem interface for the new subsystem
- registers it
- add common methods like processMessage

linked to issue #3824

## Changes

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

#3824

## Primary Reviewer

@axaysagathiya

2024-04-02 12:57 UTC, EclesioMeloJunior requested changes

2024-04-02 12:57 UTC, EclesioMeloJunior commented on dot/parachain/collator-protocol/collator_side.go
> +	propagate := false
use `const propagate = false`

2024-04-02 12:57 UTC, EclesioMeloJunior commented on dot/parachain/collator-protocol/collator_side.go
> +	}
use iota to each collator message type index

```go
type collatorProtocolMessage int
const (
   Declare collatorProtocolMessage = iota
   AdvertiseCollation
   CollationSeconded
)
```

2024-04-02 12:57 UTC, EclesioMeloJunior commented on dot/parachain/collator-protocol/collator_side.go
> +
This does not look useful for me, the unique error case of `RegisterNotificationsProtocol` is if the message type, in this case `CollationMsgType`, is already registered, which means that the legacy protocol will never be registered.

Would be nice if we could both of these protocols, but as I said `RegisterNotificationsProtocol` method can only hold one protocol per each message type, so I've created an issue to implement these missing part https://github.com/ChainSafe/gossamer/issues/3846

2024-04-05 12:24 UTC, kishansagathiya commented on dot/parachain/collator-protocol/collator_side.go
> +
have removed legacy protocol registration.

2024-04-05 12:24 UTC, kishansagathiya commented on dot/parachain/collator-protocol/collator_side.go
> +
there might be very few nodes using legacy protocols, so it might be safe to even not support it.

2024-04-05 12:24 UTC, kishansagathiya commented on dot/parachain/collator-protocol/collator_side.go
> +	}
done

2024-04-08 12:49 UTC, EclesioMeloJunior approved these changes

2024-04-08 14:34 UTC, axaysagathiya approved these changes

2024-04-08 14:34 UTC, axaysagathiya commented on dot/parachain/collator-protocol/collator_side.go
> +	collatingOn parachaintypes.ParaID
add nolint:unused
```suggestion
	collatingOn parachaintypes.ParaID //nolint:unused
```

2024-04-09 01:37 UTC, timwu20 commented on dot/parachain/collator-protocol/collator_side.go
> +	collatorProtocolV, err := collatorProtocol.Value()
```suggestion
	collatorProtocolVal, err := collatorProtocol.Value()
```

2024-04-09 09:42 UTC, merged