feat(lib): support `MinimumBackingVotes` runtime function call
ChainSafe/gossamer pull request #3857
Opened 2024-04-04 07:06 UTC by axaysagathiya

## Changes

- added constant for export method
- added `ParachainHostMinimumBackingVotes` function to `Instance` interface
- implemented instance method
- added test
- mockgen

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues
closes #3856 

## Primary Reviewer

@

2024-04-04 07:13 UTC, axaysagathiya commented
- From Polkadot.js I get the minimum backing votes is 2 for block hash `0x104d86ba31c8835ca4ffc5b09804302711865242ed422a95250c86d63e6ba3f3`
- but in test I get 0, instead of 2


![Screenshot from 2024-04-03 12-26-35](https://github.com/ChainSafe/gossamer/assets/40173579/e78119de-505a-4659-bd74-8eaa7a46fdec)
![Screenshot from 2024-04-03 12-30-28](https://github.com/ChainSafe/gossamer/assets/40173579/6391f710-ef3c-46e1-85f5-433a69d93c49)

2024-04-06 17:26 UTC, axaysagathiya commented on lib/runtime/wazero/instance.go
> +		ExportMemory("memory", 24).
Not sure about this value

2024-04-08 10:39 UTC, axaysagathiya commented on lib/runtime/wazero/instance.go
> +		ExportMemory("memory", 24).
I used `2070` as the value of `memory pages` as I got the ans [here in Slack](https://chainsafeio.slack.com/archives/CEATMPULS/p1712414223681539)

2024-04-08 12:11 UTC, kishansagathiya approved these changes
Good work! LGTM! 🎉 

There is some confusion in the wording on memory pages. At places (in polkadot-sdk), it says min pages and at places it says max pages. Let's confirm which one is it.

2024-04-08 12:45 UTC, EclesioMeloJunior commented
@kishansagathiya the max pages in polkadot-sdk from what I know is `65536` and each page can have a maximum of `65536` bytes, so the max bytes allocation is `4294967296`. Regards the `ExportMemory` method, it tells the wazero to initialize a memory buffer with size equals to the number of pages passed as argument, eg. we're passing `2070` pages which will initialize a buffer of `135659520` bytes (2070 * 65536)

2024-04-08 12:46 UTC, EclesioMeloJunior approved these changes
LGTM

2024-04-08 13:18 UTC, P1sar requested changes

2024-04-08 13:18 UTC, P1sar commented on lib/runtime/wazero/instance.go
> +		ExportMemory("memory", 2070).
First of all, no magic variables please.  This should be const var with specific name. 
Secondly, if this value static it should be 65k. Please refer to our slack thread for more details.

2024-04-08 14:10 UTC, axaysagathiya commented on lib/runtime/wazero/instance.go
> +		ExportMemory("memory", 2070).
basti replied on element chat,
> Basti.await
> These values are implementation specific. They are just to optimize the memory usage
> If the instantiation would fail, we would just increase the values

So, we can use 24 now, and if we use more it will just waste the memory

2024-04-08 16:39 UTC, P1sar approved these changes

2024-04-09 03:50 UTC, axaysagathiya commented
Finally, as we decided on Slack, I'm setting the value of min memory pages to 2080.

2024-04-09 04:22 UTC, merged