feat(internal/client/state-db) pruning maintenance
ChainSafe/gossamer pull request #3956
Opened 2024-05-16 16:37 UTC by timwu20

## Changes
- `pruningWindow` which maintains a queue of changes associated to blocks which should be pruned from canonical chain
  - this enables us to be able maintain an online pruner to only store a fixed number of blocks
- `NoteCanonical` takes in a `CommitSet` which will be modified and is expected to be committed to the DB to store a journal record for the pruner to store it's own state.
- `PruneOne` takes in a `Commit` which will be modified and is expected to be committed to actually prune unneeded changes that have now fallen out of the pruning window.

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer/internal/client/state-db
```

## Issues

#3898 

## Primary Reviewer

@dimartiro

2024-05-20 01:54 UTC, dimartiro requested changes

2024-05-20 01:54 UTC, dimartiro commented on internal/client/state-db/pruning.go
> +	return toMetaKey([]byte("pruning_journal"), block)
Can we move the `[]byte("pruning_journal")` to a constant?

2024-05-20 01:54 UTC, dimartiro commented on internal/client/state-db/pruning.go
> +func newInMemDeathRowQueue[BlockHash Hash, Key Hash](db MetaDB, base uint64) (deathRowQueue[BlockHash, Key], error) {
Are you planning to create the `DbBackedDeathRowQueue` in this PR too?

2024-05-20 01:54 UTC, dimartiro commented on internal/client/state-db/pruning.go
> +	}
Why not using if? 🤔 

```suggestion
	if drqim.deathRows.At(int(index)).hash == hash {
		return haveBlockYes
	}
	return haveBlockNo
```

2024-05-20 01:54 UTC, dimartiro commented on internal/client/state-db/pruning.go
> +	}
Perhaps we should add a comment to remind that these lines only make sense if our `rw.queue.(type) == inMemDeathRowQueue`, what do you think?

2024-05-20 01:54 UTC, dimartiro commented on internal/client/state-db/pruning.go
> +		commit.Data.Deleted = append(commit.Data.Deleted, deletedKeys...)
```suggestion
		commit.Data.Deleted = append(commit.Data.Deleted, maps.Keys(pruned.deleted)...)
```

2024-05-20 01:54 UTC, dimartiro commented on internal/client/state-db/pruning.go
> +func (rw *pruningWindow[BlockHash, Key]) NextHash() (*BlockHash, error) {
Are we using this method?

2024-05-21 12:46 UTC, timwu20 commented on internal/client/state-db/pruning.go
> +	}
There used to be a `haveBlockMaybe` which I removed. I'll switch this to an if condition.

2024-05-21 12:46 UTC, timwu20 commented on internal/client/state-db/pruning.go
> +	return toMetaKey([]byte("pruning_journal"), block)
Can't make constant byte slices, and this isn't repeated to necessitate using a package level variable.

2024-05-21 12:46 UTC, timwu20 commented on internal/client/state-db/pruning.go
> +func newInMemDeathRowQueue[BlockHash Hash, Key Hash](db MetaDB, base uint64) (deathRowQueue[BlockHash, Key], error) {
No, that requires an underlying db that implements reference counting based on the substrate docs.  The only db that supports reference counting in substrate is `parity-db`.  I'm not even sure how the mechanics work specifically with regards to reference counting for the `DbBackedDeathRowQueue`, but it's only instantiated when `parity-db` is used as the underlying db.

2024-05-21 12:46 UTC, timwu20 commented on internal/client/state-db/pruning.go
> +	}
Given that we won't be supporting `parity-db` anytime soon, I don't think we need to make it explicit.  I think the journal record needs to be updated with the inserted keys for this to properly function.

2024-05-21 12:46 UTC, timwu20 commented on internal/client/state-db/pruning.go
> +func (rw *pruningWindow[BlockHash, Key]) NextHash() (*BlockHash, error) {
Yes in the next PR.

2024-05-21 14:13 UTC, dimartiro approved these changes

2024-05-28 02:23 UTC, merged