feat(lib/runtime): remove runtime type reflection in host module function definitions (with Generics)
ChainSafe/gossamer pull request #3962
Opened 2024-05-16 23:48 UTC by ec2

## Changes
Same as https://github.com/ChainSafe/gossamer/pull/3960, but it uses generics instead to enforce type safely. Keeping this as draft because I havent tested the impact on performance of using generics

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

## Primary Reviewer

@

2024-05-17 15:35 UTC, edwardmack approved these changes
This looks great.  You mention potential performance differences between this and #3960.  Are you planning to get some metrics to determine if #3962 or #3960 should be merged?

2024-05-17 15:51 UTC, ec2 commented
> This looks great. You mention potential performance differences between this and #3960. Are you planning to get some metrics to determine if #3962 or #3960 should be merged?

Yeah. @EclesioMeloJunior has a script here https://github.com/ChainSafe/gossamer/tree/development/scripts/retrieve_block

I will try it out and see which is better probably by today or Monday. Then I will post results and let y'all decide which to merge and which to close. This one is better for maintainability and readability.

2024-05-17 15:53 UTC, ec2 commented
Or you can merge #3960 first because its for sure faster. And then this one can be merged based on measured performance. In that way, we can have both in the commit history.

2024-06-10 17:47 UTC, EclesioMeloJunior commented
@ec2 since the https://github.com/ChainSafe/gossamer/pull/3960 was already merged, can we merge this one?

2024-06-10 18:02 UTC, EclesioMeloJunior requested changes
LGTM, really great changes, makes the code a lot more type safe, thanks!

2024-06-10 18:02 UTC, EclesioMeloJunior commented on lib/runtime/wazero/imports.go
> +func wrap1[T0 WasmParamType](f func(ctx context.Context, m api.Module, a T0)) api.GoModuleFunc {
You can define a type for the `f` function like to make the functions less verbose and the types clear in the top of the file. 

```go
type noArg func(ctx context.Context, m api.Module)
type singleArg[T WasmParamType] func(ctx context.Context, m api.Module, arg1 T)
...
...
type noArgWithRet[R WasmParamType] func(ctx context.Context, m api.Module) R
...

func wrap0(f noArg) api.GoModuleFunc { ... }

func wrap1[T0 WasmParamType](f singleArg[T]) api.GoModuleFunc { ... }

func wrap0ret[R WasmParamType](f noArgWithRet[R]) api.GoModuleFunc {
```

2024-06-13 02:03 UTC, EclesioMeloJunior commented
Depends on https://github.com/ChainSafe/gossamer/pull/4041

2024-06-13 13:26 UTC, jimjbrettj approved these changes
nice work!

2024-06-13 14:07 UTC, EclesioMeloJunior approved these changes

2024-06-13 14:37 UTC, merged