fix(lib/runtime/storage): `NextKeys` failed after a transaction commit
ChainSafe/gossamer pull request #4058
Opened 2024-06-20 22:29 UTC by EclesioMeloJunior

## Changes

- Remove the usage of `sortedKeys`
- While under a transaction compare the next key acquire from the state with the one acquire from the `upserts` from the current transaction, the lower one is returned

## Tests

```sh
go test -run ^TestNextKeysUsingDifferentTransactions$ github.com/ChainSafe/gossamer/lib/runtime/storage
go test -run ^TestNextKeysWhitinSameTransaction$ github.com/ChainSafe/gossamer/lib/runtime/storage
```

## Issues

- Closes

2024-06-21 14:41 UTC, timwu20 commented
Looks like some tests are failing? I've also added @dimartiro to review this.

2024-06-21 14:42 UTC, timwu20 requested changes
Looks like some tests are failing? I've also added @dimartiro to review this.

2024-06-21 15:49 UTC, dimartiro requested changes

2024-06-21 15:49 UTC, dimartiro commented on lib/runtime/storage/trie.go
> +			if currentTxNextKey < string(nextKey) {
If our trie is empty and we start with transactions `nextKey` is nil and we have to return the nextKey from tx

```suggestion
			if nextKey == nil || currentTxNextKey < string(nextKey) {
```

2024-06-21 16:25 UTC, dimartiro requested changes
Some more findings to fix

2024-06-21 16:25 UTC, dimartiro commented on lib/runtime/storage/trie.go
> +	if err != nil {
This could be an issue if we start with a trie without children

2024-06-21 16:25 UTC, dimartiro commented on lib/runtime/storage/trie.go
> +				if currentTxChildNextKey < string(childNextKey) {
```suggestion
				if childNextKey == nil || currentTxChildNextKey < string(childNextKey) {
```

2024-06-21 19:33 UTC, EclesioMeloJunior commented on lib/runtime/storage/trie.go
> +	if err != nil {
How can it be a problem, after `GetChild` I perform a check `if child == nil {return nil, nil}`

2024-06-21 19:35 UTC, EclesioMeloJunior commented on lib/runtime/storage/trie.go
> +	if err != nil {
Okay, I got it, if there is not child then we can miss a child in the current transaction.

2024-06-21 22:39 UTC, dimartiro commented on lib/runtime/storage/trie.go
> +	if err != nil {
The problem is that you are going to return an error instead of looking for the key in the current tx

2024-06-21 22:55 UTC, dimartiro commented
@EclesioMeloJunior I think there could be an issue with this approach.

Let's say we have a trie with these keys:

```
"acc:abc123:ddd"
"acc:abc123:eee"
```

If we start a transaction and delete the key `acc:abc123:ddd`, if we ask for the `nextKey` of `acc:abc123` during that transaction, this will return `acc:abc123:ddd` even if it is deleted, because we are using the underlying trie to get the nextKey and we are not ignoring the deleted keys during this transaction.

In my opinion, this could be challenging to solve without knowing the full keys list or without adding a function in the trie to ignore keys while calculating the nextKey, which, I think, is not the responsibility of the trie.

I suggest temporarily keeping the `sortedKeys` approach for the main trie and transactions, because this will be solved in the middle term when we start using lazy loading and the blockchainDB overlays will use an `inMemoryDB` that will allow us to 'simulate' a similar behavior we had when we were using the trie snapshots.

Here is a test you can use to debug what I'm saying:

```go
func TestNextKeysAfterDeletingKeys(t *testing.T) {
    ts := NewTrieState(inmemory_trie.NewEmptyTrie())

    keys := [][]byte{
        []byte("acc:abc123:ddd"),
        []byte("acc:abc123:eee"),
        []byte("acc:abc123:fff"),
    }

    for _, key := range keys {
        require.NoError(t, ts.Put(key, []byte("0x10")))
    }

    ts.StartTransaction()
    require.NoError(t, ts.Delete([]byte("acc:abc123:ddd")))

    prefix := []byte("acc:abc123")
    nextKey := ts.NextKey(prefix)

    require.NotNil(t, nextKey)
    require.Equal(t, []byte("acc:abc123:eee"), nextKey)

    ts.CommitTransaction()
}

2024-07-03 16:24 UTC, EclesioMeloJunior commented
Closing this PR since I will work in a new one with the actual implementation

2024-07-03 16:24 UTC, closed without merging