feat(pkg/trie): Implement `TrieIterator` for `InMemoryTrie`
ChainSafe/gossamer pull request #4073
Opened 2024-07-05 14:11 UTC by EclesioMeloJunior

## Changes

- Changes the `TrieIterator` interface, defining just the methods implemented by a iterator
- Changes the `TrieRead` interface, now it has the methods `Entries(), NextKey(), GetKeysWithPrefix` and I've added two more: `Iter(), PrefixedIter(prefix)`
- The PR aims to reduce the dependency of `t.sortedKeys` map from `lib/runtime/storage` and query the state when needed.

## Tests

```sh
go test -timeout 10m -run ^TestNextKeys$ github.com/ChainSafe/gossamer/lib/runtime/storage --tags=integration -v
go test -timeout 10m -run ^TestInMemoryTrieIterator$ github.com/ChainSafe/gossamer/pkg/trie/inmemory --tags=integration -v
```

## Issues

- Rework of https://github.com/ChainSafe/gossamer/pull/4058
- Closes https://github.com/ChainSafe/gossamer/issues/4074

2024-07-05 18:37 UTC, dimartiro requested changes
Thanks for implementing it! It would be great if we were able to create a generic Iterator that works for the 2 types of tries but I think it would imply a bigger refactor.

I left some comments for small changes and a discussion about the use of a predicate, but overall I thing the implementation is correct

2024-07-05 18:37 UTC, dimartiro commented on pkg/trie/triedb/triedb_iterator.go
> +func (i *TrieDBIterator) NextKeyFunc(predicate func(nextKey []byte) bool) (nextKey []byte) {
IMO this is responsibility of the caller in order to follow the Go philosophy and doing it more verbose.
The caller should execute `NextEntry()` skipping the ones it is not interested in instead of using a predicate function
In case we want to keep this logic I'd suggest to rename it to `NextKeyWithFilter`

2024-07-05 18:37 UTC, dimartiro commented on pkg/trie/triedb/triedb_iterator.go
>  	for key := i.NextKey(); bytes.Compare(key, targetKey) < 0; key = i.NextKey() {
If we want to keep the `NextKeyFunc` logic I think we can refactor this to use it and skip the keys that are `<` than the `targetkey`

2024-07-05 18:37 UTC, dimartiro commented on pkg/trie/inmemory/interator_test.go
> +// Copyright 2024 ChainSafe Systems (ON)
Check the name of the file, it says `interator` instead of `iterator` 😛

2024-07-05 19:06 UTC, EclesioMeloJunior commented on pkg/trie/triedb/triedb_iterator.go
> +func (i *TrieDBIterator) NextKeyFunc(predicate func(nextKey []byte) bool) (nextKey []byte) {
>  in order to follow the Go philosophy and doing it more verbose

I would say that making it more verbose is different to make things explicit. I don't like verbosity code but I prefer the explicit code where the logic is clear to understand, for example:
````


 Having the `NextKeyFunc` or even a `NextEntryFunc` makes the API and the responsibility of the iterator explicit enough to the caller. Also I tried to follow the Golang function nomenclature (eg. `slices.BinarySearchFunc`, `slices.EqualFunc`, `maps.DeleteFunc`)

2024-07-08 01:13 UTC, dimartiro commented on pkg/trie/triedb/triedb_iterator.go
> +func (i *TrieDBIterator) NextKeyFunc(predicate func(nextKey []byte) bool) (nextKey []byte) {
Ok I like your point. It is explicit enough 👍

2024-07-08 19:47 UTC, dimartiro approved these changes

2024-07-10 09:43 UTC, jimjbrettj commented on pkg/trie/inmemory/interator_test.go
> +// Copyright 2024 ChainSafe Systems (ON)
This one still needs to be updated

2024-07-10 09:46 UTC, jimjbrettj approved these changes
lgtm

2024-07-10 15:26 UTC, merged