fix(runtime/storage): add child prefix check
ChainSafe/gossamer pull request #4143
Opened 2024-08-23 08:15 UTC by jimjbrettj

## Changes

- When clearing a prefix from storage, first do a check to make sure the prefix does not contain the child prefix

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues
closes #4142

2024-08-23 08:20 UTC, jimjbrettj commented on lib/runtime/wazero/imports.go
> +	return 0
Wanted to double-check that we want to ignore this case and not panic. Also here wanted to make sure 0 was the correct value to return

2024-08-23 12:51 UTC, EclesioMeloJunior reviewed
We should not panic but return none Afaik

2024-08-23 14:48 UTC, EclesioMeloJunior requested changes

2024-08-23 14:48 UTC, EclesioMeloJunior commented on lib/runtime/wazero/imports.go
> +		logger.Warnf("cannot clear prefix that is part of or contains a child storage key")
```suggestion
	if !bytes.HasPrefix(prefix, childStorageKeyPrefix) {
		storage.ClearPrefix(prefix)
	} else {
		logger.Warnf("cannot clear a child prefix key: 0x%x", prefix)
```

2024-08-23 14:48 UTC, EclesioMeloJunior commented on lib/runtime/wazero/imports.go
> +	if !bytes.HasPrefix(prefix, childStorageKeyPrefix) {
instead of making the logic nested, you can check the prefix before calling the storage function, you can place the check after reading the prefix from memory, like:

```go
prefix := read(m, prefixSpan)
logger.Debugf("prefix: 0x%x", prefix)

if bytes.HasPrefix(prefix, childStorageKeyPrefix) {
    logger.Warnf("cannot clear child prefix: 0x%x", prefix)
    // the value you must return is a storage result enum
    // that can be built by calling toKillStorageResultEnum func
    encBytes, err := toKillStorageResultEnum(false, 0)
    if err != nil { ... }
    
    valueSpan := mustWrite(m, rtCtx.Allocator, encBytes)
    return valueSpan
}

... rest of the logic here 
```

2024-08-26 07:01 UTC, jimjbrettj commented on lib/runtime/wazero/imports.go
> +		logger.Warnf("cannot clear prefix that is part of or contains a child storage key")
Before we panicked if there was an error clearing the prefix, is there a reason you want to modify this behavior?

2024-08-26 15:09 UTC, EclesioMeloJunior commented on lib/runtime/wazero/imports.go
> +		logger.Warnf("cannot clear prefix that is part of or contains a child storage key")
oh, just saw, nevermind!

2024-08-26 15:10 UTC, EclesioMeloJunior approved these changes

2024-08-28 08:56 UTC, P1sar approved these changes

2024-09-03 07:04 UTC, merged