docs(parachain): design for prospective-parachains
ChainSafe/gossamer pull request #4348
Opened 2024-11-28 03:00 UTC by EclesioMeloJunior

## Changes

Add the design document for the prospective-parachains subsystem.

## Tests

N/A

## Issues

- Closes https://github.com/ChainSafe/gossamer/issues/4241

2024-12-02 11:41 UTC, P1sar commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +![IMG_944F8C1D62F0-1](https://hackmd.io/_uploads/SJ3KA0m7kg.jpg)
I do not have access to this image and overall, I guess, it would be better if we upload images to repo. wdyt?

2024-12-02 11:41 UTC, P1sar commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +![IMG_88FB30D4B931-1](https://hackmd.io/_uploads/rysElgE71x.jpg)
same as above about images

2024-12-02 14:07 UTC, timwu20 requested changes

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +This structure does not care if candidates form a chain, it only stores candidates and holds "links" to a `CandidateEntry`, those links are
Can you add links to the polkadot repo code for these types?

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +`input -> execution -> head data (parachain block head)`, it is called head data because it is a `Vec<u8>`, what this head data contains is not for the validator, what we care is the hash of it!
```suggestion
`input -> execution -> head data (parachain block head)`, it is called head data because it is a `Vec<u8>`, what this head data contains is not for the validator, what we care is the *hash* of it.
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +This is a node that is part of a `BackedChain`. When we create a new fragment we should make sure that the candidate is valid under the operating constraints. We use the constraints to build an expec
```suggestion
This is a node that is part of a `BackedChain`. When we create a new fragment we should make sure that the candidate is valid under the operating constraints. We use the constraints to build an expected persisted validation data and compare with the one we got from the candidate. A fragment node is always backed and it is generated from a `CandidateEntry`.
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +###### RevertToParentHash
```suggestion
#### RevertToParentHash
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +- Relay parent does not move backwards: given our earliest relay parent (the earliest ancestor that a candidate can use as its context) the current candidate's relay parent should not be befor it.
```suggestion
- Relay parent does not move backwards: given our earliest relay parent (the earliest ancestor that a candidate can use as its context) the current candidate's relay parent should not be before it.
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +1. Lets build a queue of candidates in the backed chain (a.k.a green letters) and we will use an extra info called has potential, saying that the candidate is good to stay connected (even if they for
```suggestion
1. Lets build a queue of candidates in the backed chain (a.k.a green letters) and we will use an extra info called "has potential", which means that the candidate is good to stay connected (even if they form a fork).
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +3. for each children:
```suggestion
3. for each child:
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +    3.1. is the children in the unconnected hash?
```suggestion
    3.1. is the child in the unconnected hash set?
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +    3.2. did we already visited this children?
```suggestion
    3.2. did we already visited this child?
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +    3.3. is the candidate and the child potentials?
```suggestion
    3.3. does the candidate and the child have potential?
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +Lets apply the chain from image against the steps defined above, first things first, we should build the queue from our `backed chain`.
```suggestion
Lets apply the chain from image against the steps defined above, first things first, we should build the queue from our backed chain.
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/fragment-chain.md
> +as there is no more children... lets pop `(C, true)` from the queue, mark it as visited and iterate over its children!
```suggestion
as there are no more children... lets pop `(C, true)` from the queue, mark it as visited and iterate over its children!
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/prospective-parachains.md
> +Try getting N backable candidate hashes along with their relay parents for the given parachain, under the given relay-parent hash, which is a descendant of the given ancestors. Timed out ancestors sh
```suggestion
Try getting N backable candidate hashes along with their relay parents for the given parachain, under the given relay-parent hash, which is a descendant of the given ancestors. Timed out ancestors should not be included in the collection. N should represent the number of scheduled cores of this `ParaId`. A timed out ancestor frees the cores of all of its descendants, so if there's a hole in the supplied ancestor path, we'll get candidates that backfill those timed out slots first. It may also return less/no candidates, if there aren't enough backable candidates recorded.
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/prospective-parachains.md
> +Get the minimum accepted relay-parent number for each para in the fragment chain for the given relay-chain block hash. That is, if the block hash is known and is an active leaf, this returns the mini
Use `ParaID` or `ParaId` consistently throughout this document.

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/prospective-parachains.md
> +2. `overseer.ActiveLeaves` -> update the new activated leaf to the new scheduled paras, pre-populate the candidate storage with pending availability candidates and candidates from the parent leaf, po
```suggestion
2. `overseer.ActiveLeaves` -> update the new activated leaf to the new scheduled paras, pre-populate the candidate storage with pending availability candidates and candidates from the parent leaf, populate the fragment chain, add it to the implicit view. Then mark the newly deactivated leaves as deactivated and update the implicit view. Finally, remove any relay parents that are no longer part of the implicit view.
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/prospective-parachains.md
> +- Implicity View
```suggestion
- Implicit View
```

2024-12-02 14:07 UTC, timwu20 commented on docs/docs/design/parachain-protocol/prospective-parachains.md
> +This handler receives the candidate hash and its parachain id and will try to mark the candidate hash as backed, the candidate should already exists in the parachain fragment chain otherwise this han
```suggestion
This handler receives the candidate hash and its parachain id and will try to mark the candidate hash as backed, the candidate should already exist in the parachain fragment chain otherwise this handler will fail, if the candidate is already marked as backed nothing happens.
```

2024-12-05 08:35 UTC, haikoschol requested changes
Can you move the assets to `docs/docs/assets/img/parachain-protocol/` and the markdown file to `docs/docs/design`? I know we agreed on `docs/docs/design/parachain-protocol`, but somehow we landed on just `docs/docs/design` when we merged #4349.

And ideally link the `.md` from one of the other design docs or from `mkdocs.yml`.

2024-12-05 08:35 UTC, haikoschol commented on docs/docs/design/parachain-protocol/prospective-parachains.md
> +of work within
```suggestion
```

2024-12-05 08:35 UTC, haikoschol commented on docs/docs/design/parachain-protocol/prospective-parachains.md
> +The subsystem must be registered with the overseer and handle two subsystem-specific messages from it:
```suggestion
The subsystem must be registered with the overseer and handle six subsystem-specific messages from it:
```

2024-12-10 09:05 UTC, haikoschol approved these changes

2024-12-11 14:31 UTC, timwu20 approved these changes

2024-12-11 14:31 UTC, timwu20 commented on docs/docs/design/fragment-chain.md
> +##### Trim Unelegible Forks
```suggestion
##### Trim Inelegible Forks
```

2024-12-11 14:31 UTC, timwu20 commented on docs/docs/design/fragment-chain.md
> +What is does is a deapth breadth-first search looking for candidates in the Candidate Storage that has no potential that is children of valid backed candidates.
```suggestion
It does a depth breadth-first search looking for candidates in the Candidate Storage that have no potential and that are children of valid backed candidates.
```

2024-12-11 14:31 UTC, timwu20 commented on docs/docs/design/fragment-chain.md
> +Consider the following chain, the green letters forms the [`BackedChain`](https://github.com/paritytech/polkadot-sdk/blob/3d8da815ecd12b8f04daf87d6ffba5ec4a181806/polkadot/node/core/prospective-parac
```suggestion
Consider the following chain, the green letters forms the [`BackedChain`](https://github.com/paritytech/polkadot-sdk/blob/3d8da815ecd12b8f04daf87d6ffba5ec4a181806/polkadot/node/core/prospective-parachains/src/fragment_chain/mod.rs#L596) while the red letters are candidates placed in the `Unconnected` candidate storage, drawing them (without all the maps and hashes here and there) we can have something similar to the image below.
```

2024-12-11 14:31 UTC, timwu20 commented on docs/docs/design/fragment-chain.md
> +Now lets trim the unelegible forks out, but first we need to define the steps:
```suggestion
Now lets trim the inelegible forks out, but first we need to define the steps:
```

2024-12-12 15:42 UTC, merged