chore(candidate-backing): update active leaves
ChainSafe/gossamer pull request #4383
Opened 2024-12-06 10:54 UTC by axaysagathiya

## Changes

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

2025-02-19 19:19 UTC, EclesioMeloJunior commented on dot/parachain/backing/candidate_backing.go
> +	validators         []parachaintypes.ValidatorID
What is the diff between ValidatorID and ValidatorIndex?

2025-02-19 19:36 UTC, axaysagathiya commented on dot/parachain/backing/candidate_backing.go
> +	validators         []parachaintypes.ValidatorID
ValidatorID is public key and ValidatorIndex is uint32 type which is lightweight replacement of the `ValidatorId`

2025-02-20 14:31 UTC, EclesioMeloJunior commented on dot/parachain/backing/candidate_backing.go
> +	validators         []parachaintypes.ValidatorID
So given that we have both types and their names is very close which can cause ambiguity, I would suggest to rename `ValidatorID` to `ValidatorPublicKey` so we remove any mistakes when referring to some type.

2025-02-20 14:50 UTC, EclesioMeloJunior requested changes

2025-02-20 14:50 UTC, EclesioMeloJunior commented on dot/parachain/backing/candidate_backing.go
> +type CandidateBacking struct { // TODO: Update comments in this struct
will be addressed on this PR?

2025-02-20 14:50 UTC, EclesioMeloJunior commented on dot/parachain/backing/candidate_backing.go
> +	perLeaf map[common.Hash]*activeLeafState // TODO: Remove this field
will be addressed on this PR?

2025-02-20 14:50 UTC, EclesioMeloJunior commented on dot/parachain/backing/per_relay_parent_state.go
> +	introduceCandidateErr, ok := <-chIntroduceCandidate
to effectively block and wait on the channel you must not read the `ok` value. 
```go
        // waits until the channel returns some value
	introduceCandidateErr := <-chIntroduceCandidate
	
	// don't wait
	// if there is some value ready in the channel it will read 
	// if there is no value ready then it will only get the ok
        //    - (true if the ch is open, false if the ch is closed)
	// but will not block
        introduceCandidateErr, ok := <-chIntroduceCandidate
```

```suggestion
	introduceCandidateErr := <-chIntroduceCandidate
```

2025-02-20 14:59 UTC, axaysagathiya commented on dot/parachain/backing/candidate_backing.go
> +	validators         []parachaintypes.ValidatorID
Agree, Can we address this in separate PR as none of these types introduced in this PR?

2025-02-20 15:01 UTC, axaysagathiya commented on dot/parachain/backing/candidate_backing.go
> +	perLeaf map[common.Hash]*activeLeafState // TODO: Remove this field
Nope, We have multiple issues to avoid using this field. eventually this field will be removed.
I will remove the todo coment from here.

2025-02-20 15:09 UTC, EclesioMeloJunior commented on dot/parachain/backing/candidate_backing.go
> +	validators         []parachaintypes.ValidatorID
yes, we can! can you open an issue for that?

2025-02-20 20:14 UTC, freddyli7 commented on dot/parachain/backing/per_relay_parent_state.go
> +	introduceCandidateErr, ok := <-chIntroduceCandidate
I don't think the logic will continue if you read if the chan is open/close, it will still be blocked until next value is ready

2025-02-21 05:01 UTC, axaysagathiya commented on dot/parachain/backing/candidate_backing.go
> +	validators         []parachaintypes.ValidatorID
I have raised an issue to rename the type https://github.com/ChainSafe/gossamer/issues/4552

2025-02-21 05:06 UTC, axaysagathiya commented on dot/parachain/backing/candidate_backing.go
> +type CandidateBacking struct { // TODO: Update comments in this struct
Yes. Thanks for pointing out this.

2025-02-21 05:40 UTC, axaysagathiya commented on dot/parachain/backing/per_relay_parent_state.go
> +	introduceCandidateErr, ok := <-chIntroduceCandidate
@EclesioMeloJunior That's not true.
`Ok` will be false only when channel is closed.

if there is no value ready then it will wait to get the value. 
You can check running this code https://go.dev/play/p/5349f7J80ug

2025-02-21 16:01 UTC, EclesioMeloJunior commented on dot/parachain/backing/per_relay_parent_state.go
> +	introduceCandidateErr, ok := <-chIntroduceCandidate
Oh, okay, thanks for the clarification! 👍

2025-02-21 16:07 UTC, EclesioMeloJunior approved these changes
LGMT

2025-02-25 03:04 UTC, timwu20 commented on dot/parachain/backing/active_leaves_update.go
> +	uniqueAllowedRelayParents := make(map[common.Hash]struct{})
```suggestion
	uniqueAllowedRelayParents := make(map[common.Hash]any)
```
I usually just use `nil` when populating hash sets (empty value maps).

2025-02-25 03:04 UTC, timwu20 commented on dot/parachain/backing/per_relay_parent_state.go
> +	numOfCores := uint32(len(validatorGroups.Validators))
would this ever overflow?

2025-02-25 07:12 UTC, axaysagathiya commented on dot/parachain/backing/active_leaves_update.go
> +	uniqueAllowedRelayParents := make(map[common.Hash]struct{})
I see your approach of using `nil` as the value in a `map[common.Hash]any`, which keeps the map structure simple. However, I personally prefer using `struct{}` for semantic clarity.

Using **struct{}** makes it explicitly clear that this map is being used as a set rather than implying that values might have significance.

That said, if there's a strong preference for `any` in our codebase, I'm happy to align with the convention! Let me know what you think.

2025-02-25 07:29 UTC, axaysagathiya commented on dot/parachain/backing/per_relay_parent_state.go
> +	numOfCores := uint32(len(validatorGroups.Validators))
I don't think. because core index of of type `uint32`. So it's impossible to have a number of core more than `MaxUint32`.
```
type CoreIndex struct {
	Index uint32 `scale:"1"`
}
```

2025-02-25 14:30 UTC, timwu20 commented on dot/parachain/backing/active_leaves_update.go
> +	uniqueAllowedRelayParents := make(map[common.Hash]struct{})
After looking into it, I found out that storing `any` uses way more memory than `struct{}`

2025-02-25 14:53 UTC, axaysagathiya commented on dot/parachain/backing/per_relay_parent_state.go
> +	// claimQueue parachaintypes.ClaimQueue
remove this

2025-02-25 15:02 UTC, freddyli7 approved these changes
looks good to me on the high level side.

2025-02-25 16:44 UTC, timwu20 approved these changes

2025-02-25 17:48 UTC, merged