feat(internal/client/db) Introduce `api.Backend` interface and `db.Backend` implementation
ChainSafe/gossamer pull request #4405
Opened 2024-12-12 17:59 UTC by timwu20

## Changes

### `api.Backend`

This is the client backend interface where trie state can be retrieved for a given block hash. State pruning achieved using `StateDB`, and historical block pruning is performed by `blockchainDB`. 

#### `api.AuxStore`

This is an interface that provides access to an auxiliary database.  This database is not fork-aware.  This interface is embedded into `api.Backend`

#### `Backend.BeginOperation`

Begins a new block insertion transaction.  What is returned is something that implements `api.BlockImportOperation`.

#### `Backend.BeginStateOperation`

Notes the `BlockImportOperation` to contain a state transition. 

#### `Backend.CommitOperation`

Commits a `BlockImportOperation` into the backend.

#### `Backend.FinalizeBlock`

Finalizes a block for a given hash.  Takes an optional justification to be stored.

#### `Backend.PinBlock` and `Backend.UnpinBlock`

This will pin a block into memory to avoid it from being pruned during state pruning or block pruning. `UnpinBlock` will allow the block to be pruned from memory.

#### `Backend.StateAt`

Retrieve the state at a given block.  Returns a `statemachine.Backend` implementation which will allow you to query state, but not mutate the state.

#### `Backend.GetImportLock`

Returns a pointer to the shared `sync.RWMutex` for the backend.  NOTE: the backend doesn't actually acquire the lock by itself, this is supposed to be used by the callers of `api.Backend` to handle concurrent block imports.  

### `api.BlockImportOperation`

An implementation of this interface is returned you by calling `api.Backend.BeginOperation`.  This keeps track of the inserted block data and state mutations that will be commited into the backend using `api.Backend.CommitOperation`.

#### `BlockImportOperation.State`

Returns the pending state for this block.  Can be `nil` if no state is associated.

#### `BlockImportOperation.SetBlockData`

Sets block data to the operation.  The header, body, indexed body, and justifications can be set.  The state of the block can be set as `Normal`, `Best` and `Final`.

#### `BlockImportOperation.SetGenesisState`

Accepts a `storage.Storage` which holds all the top trie and child trie changes.  Accepts a `commit` boolean which will determine whether or not the changes will be commited to the underlying database.

#### `BlockImportOperation.UpdateStorage`

Updates the top level trie as well as child tries.

#### `BlockImportOperation.InsertAux`

Insert/update auxiliary data.

#### `BlockImportOperation.MarkFinalized`

Marks the incoming block as finalized.  Accepts an optional justification.

#### `BlockImportOperation.MarkHead`

Marks the incoming block as the new head.  Will override the backend best block rule.

### `db.Backend`

This is the default implementation of `api.Backend`.  Calling `Backend.BeginOperation` will return a `db.BlockImportOperation` which implements `api.BlockImportOperation`.  

#### `db.NewBackend`

This is the constructor for `db.Backend`.  It accepts two parameters: 

  - `dbConfig` which is an instance of `DatabaseSettings`
  - `canonicalizationDelay` which represents the delay in number of blocks that canonicalization/finalization will enact on the backend.  

#### `DatabaseSettings`

This type represents the configurable settings for `db.Backend`.  The maximum size of the trie cache in bytes can be set.  `statedb.PruningMode` can be set to alter how the trie is pruned.  `BlocksPruning` can be set to `KeepAll`, `KeepFinalized` or `KeepSome` which will constrain the amount of blocks to a certain number of finalized blocks.

#### `db.Backend` dependencies

This is a quick overview on the introduced dependencies for `db.Backend`.

##### `offchain.LocalStorage`

Used for offchain storage.  Will store in the underlying DB.

##### `dbGenesisStorage`

A private type to represent the genesis state when we don't want to commit the state to the underlying database.  

### `db.BlockImportOperation`

This is the implementation of `api.BLockImportOperation` which is utilized by `db.Backend`.  The introduced dependencies are outlined below.

#### `db.refTrackingState`

This is used within `db.BlockImportOperation` as a reference to the trie backend as well as the underlying database and `statedb.StateDB`.  It stores an optional parent hash.

#### `db.pendingBlock`

A private type to represent a pending block.

### Other Notable Additions

#### `blockchain.TreeTroute`

A type with an associated `NewTreeRoute` constructor that represents a block tree route.

#### `kvdb.KeyValueDB`

An interface for a database that deal with "column families" which are distinct tables within a database.  This is essentially the interface that a key value database must conform to.

##### `memorykvdb.MemoryKVDB`

An implementation of `kvdb.KeyValueDB` completely in memory.  Used only in tests.

### `database.DBAdapter`

A helper type that wraps a `kvdb.KeyValueDB` that implements `database.Database` interface. Supports the reference counting required for `database.Database` by adding counter records to the underlying database.

### `saturating` package

This package introduces `Sub` and `Into` which is used for saturating operations for unsigned integers.  This is to ensure we don't overflow minimum and maximum values when casting between unsigned integer types.

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

closes #3900

2024-12-20 12:26 UTC, haikoschol commented on internal/client/api/backend.go
> +// Keeps hold if the inserted block state and data.
```suggestion
// Keeps hold of the inserted block state and data.
```

2024-12-20 12:26 UTC, haikoschol commented on internal/client/api/backend.go
> +	// Newly finalized block (implicitly best).
Why does final imply best? And if that's the case, wouldn't `NewBlockState.IsBest()` return `nbs == NewBlockStateBest || nbs == NewBlockStateFinal`?

2024-12-20 12:26 UTC, haikoschol commented on internal/client/api/backend.go
> +	SetBlockData(
```suggestion
	AppendBlockData(
```

2024-12-20 12:26 UTC, haikoschol commented on internal/client/api/backend.go
> +	// Mark a block as new head. If both block import and set head are specified, set head
I don't understand the second sentence. It sounds like it's describing a method with two parameters, but `MarkHead()` only has one. 🤔

2024-12-20 12:26 UTC, haikoschol commented on internal/client/api/backend.go
> +	BeginOperation() (BlockImportOperation[N, H, Hasher, Header, E], error)
Should this have a parameter of type `H`? If not, what is meant by "this is called with all-zero hash"?

2024-12-20 12:26 UTC, haikoschol commented on internal/client/db/backend.go
> +type DatabaseSettings struct {
just for consistency consider
```suggestion
type DatabaseConfig struct {
```

2024-12-20 12:26 UTC, haikoschol commented on internal/client/db/backend.go
> +		panic("only one block per operation is allowed")
Should this really be a panic considering the method returns `error` but doesn't actually use it?

2024-12-20 12:26 UTC, haikoschol commented on internal/client/db/backend.go
> +// The pruning window is how old a block must be before the state is pruned.
This comment sounds like there's a parameter for the pruning window. AFAICT, the pruning window is set *iff* `dbConfig.PruningMode` is set to `PruningModeConstrained` and `PruningModeConstrained.MaxBlocks` is non-nil, correct?

And what is `canonicalizationDelay`? Is it the number of blocks after which non-canonical nodes are discarded?

2024-12-20 12:26 UTC, haikoschol commented on internal/client/db/backend.go
> +	bestNumber := saturating.Into[N, uint64](b.blockchain.Info().BestNumber)
```suggestion
	bestNumber := saturating.Into[N, uint64](info.BestNumber)
```

2024-12-20 12:26 UTC, haikoschol commented on internal/client/db/backend.go
> +						for i := int32(0); i < rc; i++ {
Will this loop ever be executed if `rc` is negative and `i` starts at 0, thus always being larger than `rc`?

2024-12-20 12:26 UTC, haikoschol commented on internal/client/db/utils.go
> +// Otherwise RocksDb will fail to open database && check its type.
`s/RocksDb/pebble/`?

2024-12-20 12:26 UTC, haikoschol commented on internal/client/state-db/pruning.go
> +	// An index that maps each key from death_rows to block number.
```suggestion
	// An index that maps each key from deathRows to block number.
```

2024-12-20 12:26 UTC, haikoschol commented on internal/kvdb/kvdb.go
> +// Insert a key-value pair in the transaction. Any existing value will be overwritten upon write.
```suggestion
// Delete the value at the given key.
```

2024-12-20 12:26 UTC, haikoschol commented on internal/kvdb/kvdb.go
> +// The KeyVablueDB deals with "column families", which can be thought of as distinct
```suggestion
// The KeyValueDB deals with "column families", which can be thought of as distinct
```

2025-01-06 17:43 UTC, timwu20 commented on internal/client/api/backend.go
> +	// Newly finalized block (implicitly best).
Yea... this doesn't make a lot of sense.  Just cause a block is finalized doesn't mean it's the best block.  It is definitely within the best block chain, but doesn't make it the best block. I'll revise the comment.

2025-01-06 17:43 UTC, timwu20 commented on internal/client/api/backend.go
> +	SetBlockData(
I'm going to keep it as is, and revise the comment.  It's not actually appending block data to existing block data, but just setting the block data as part of the transaction.

2025-01-06 17:43 UTC, timwu20 commented on internal/client/api/backend.go
> +	// Mark a block as new head. If both block import and set head are specified, set head
I'll revise this comment to be clearer.

2025-01-06 17:43 UTC, timwu20 commented on internal/client/api/backend.go
> +	BeginOperation() (BlockImportOperation[N, H, Hasher, Header, E], error)
The zero case of whatever satisfies `runtime.Hash`.  In our case `hash.H256` will be an all zero hash.

2025-01-06 17:58 UTC, timwu20 commented on internal/client/db/backend.go
> +		panic("only one block per operation is allowed")
They panic in the rust code, but I agree with you, I think returning an error in this case is fine.

2025-01-06 17:58 UTC, timwu20 commented on internal/client/db/backend.go
> +// The pruning window is how old a block must be before the state is pruned.
the pruning mode can be `PruningModeConstrained` or `PruningModeArchiveCanonical` which only keeps finalized history.  There are two pruning settings actually in `DatabaseSettings` the state pruning as well as the block history pruning.

`canonicalizationDelay` represents the number of blocks it waits to actually canonicalize the block and initiate pruning based on canonicalization.  I'll add this to the comment.

2025-01-06 17:58 UTC, timwu20 commented on internal/client/db/backend.go
> +						for i := int32(0); i < rc; i++ {
really good catch!

2025-01-06 17:58 UTC, timwu20 commented on internal/client/db/utils.go
> +// Otherwise RocksDb will fail to open database && check its type.
I'll remove this.

2025-01-07 06:45 UTC, haikoschol approved these changes

2025-01-09 13:33 UTC, dimartiro requested changes
overall looks good but I have some suggestions that want to discuss.
Apart from that I'd suggest to follow the godoc conventions when documenting exported struct and functions, I noticed you are following it but not always

2025-01-09 13:33 UTC, dimartiro commented on internal/client/api/backend.go
> +type NewBlockState uint
Why not to use the smaller uint? for example uint8?

```suggestion
type NewBlockState uint8
```

2025-01-09 13:33 UTC, dimartiro commented on internal/client/api/backend.go
> +type BlockImportOperation[
Did we remove the linter rule to check that the godoc starts with the same type name? 🤔 I noticed we are not following that rule anymore but it is a convention in golang

2025-01-09 13:33 UTC, dimartiro commented on internal/client/db/db.go
> +	return nil, nil
Why not just

```suggestion
	return header, nil
```

2025-01-09 13:33 UTC, dimartiro commented on internal/client/api/backend.go
> +// Block insertion operation.
Can we follow the godoc conventions here?

2025-01-09 13:33 UTC, dimartiro commented on internal/client/db/backend.go
> +	isDescendantOf := utils.IsDescendantOf[H, N, Header](b.blockchain, nil)
Don't really need to explicitly set the generic types here, golang can figure them out

2025-01-09 13:33 UTC, dimartiro commented on internal/client/db/backend.go
> +var logger = log.NewFromGlobal(log.AddContext("client", "db"))
usually we use `pkg` as the context so it must be:

```suggestion
var logger = log.NewFromGlobal(log.AddContext("pkg", "db"))
```

Unless we are planning to change our logging strategy

2025-01-09 13:33 UTC, dimartiro commented on internal/client/db/utils.go
> +const NumColumns uint32 = 13
Can you add a comment to explain why 13?

2025-01-09 13:33 UTC, dimartiro commented on internal/client/state-db/noncanonical.go
> +var logger = log.NewFromGlobal(log.AddContext("client", "state-db"))
```suggestion
var logger = log.NewFromGlobal(log.AddContext("pkg", "statedb"))
```

2025-01-10 17:32 UTC, timwu20 commented on internal/client/db/backend.go
> +var logger = log.NewFromGlobal(log.AddContext("client", "db"))
I assumed the first was just the parent package.  I think it makes more sense given I want to group these loggers with context key "client".

2025-01-10 17:38 UTC, timwu20 commented on internal/client/api/backend.go
> +type BlockImportOperation[
I think that was removed from the linter since it's not always grammatically correct to start the comment with the name of the type.  I can add the type name to the comments if that's what you prefer.

2025-01-10 17:38 UTC, dimartiro commented on internal/client/db/backend.go
> +var logger = log.NewFromGlobal(log.AddContext("client", "db"))
Noup, it is a key-value pair that will be show as `client=db` in the logs.
You could use a combination of `pkg` and `module` as we are [doing here](https://github.com/ChainSafe/gossamer/blob/b6a7ef6ad8f22b9a777948d323eeea29a703ff79/lib/runtime/wazero/imports.go#L32-L35) so if you wanna filter you can filter by `pkg=db` or `module=client` as a second level.
My goal here with this comment is to try to keep our conventions

2025-01-10 17:40 UTC, dimartiro commented on internal/client/api/backend.go
> +type BlockImportOperation[
If we agree to remove that rule, we can keep it as it is in your current changes. However IMO we should follow the godoc conventions if possible.

2025-01-10 17:47 UTC, timwu20 commented on internal/client/api/backend.go
> +type BlockImportOperation[
Just to clarify I don't think we removed it, it was removed from `gofmt` or whatever linter in `golangci-lint`.

2025-01-10 17:56 UTC, timwu20 commented on internal/client/db/backend.go
> +var logger = log.NewFromGlobal(log.AddContext("client", "db"))
Ended up using a slash `/`in the values and using `pkg` as the key.  I think that's what the author of the logging library intended ([code](https://github.com/ChainSafe/gossamer/blob/604f4d4d2c697fe7403b4705b8a2cfd15399526e/tests/stress/helpers.go#L24)).

2025-01-10 18:05 UTC, dimartiro commented on internal/client/api/backend.go
> +type BlockImportOperation[
oh! ok ok. Clear now!

2025-01-10 22:23 UTC, dimartiro commented on internal/client/api/backend.go
> +type NewBlockState uint
Are we planning to change it or are you going to keep uint? 🤔

2025-01-10 22:38 UTC, timwu20 commented on internal/client/api/backend.go
> +type NewBlockState uint
I changed it. https://github.com/ChainSafe/gossamer/blob/83edb1e7bc65b5c1d569be8e9d5acaea891a3531/internal/client/api/backend.go#L17

2025-01-10 22:57 UTC, dimartiro commented on internal/client/api/backend.go
> +type NewBlockState uint
Oh sorry! It wasn't updated on my side! lgtm

2025-01-10 22:58 UTC, dimartiro approved these changes

2025-01-11 03:33 UTC, merged